version: '2'

services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=market
      - POSTGRES_PASSWORD=pass1234